# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

schedules:
- cron: '5,10 10 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - main

# resources:
#   repositories:
#   - repository: sampleapp
#     type: git
#     endpoint: JacobBaekHome
#     name: JacobBaekHome/sampleapp
variables:
  system.debug: 'true'

stages:
- stage: using_kubectl
  jobs:
  - job: job1
    displayName: deploy application to production
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'aksmonitor-cluster-sc'
        azureResourceGroup: 'aksmonitor-rg'
        kubernetesCluster: 'aksmonitor-cluster'
        command: 'get'
        arguments: 'node'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
    # - task: KubernetesManifest@1
    #   inputs:
    #     action: 'deploy'
    #     connectionType: 'azureResourceManager'
    #     azureSubscriptionConnection: 'jacobmssub(6fb4629e-0776-431c-b528-96a47c03d872)'
    #     azureResourceGroup: 'akscni-rg'
    #     kubernetesCluster: 'akscni-cluster'
    #     manifests: 'yamls/deploy-nginx.yaml'

# - stage: using_deploy_to_kubernetes
#   jobs:
#   - job: job1
#     environment:
#       name: 'akscni-cluster-env'
#     steps:
#     - task: KubernetesManifest@1
#       inputs:
#         action: 'deploy'
#         connectionType: 'azureResourceManager'
#         azureSubscriptionConnection: 'jacobmssub(6fb4629e-0776-431c-b528-96a47c03d872)'
#         azureResourceGroup: 'akscni-rg'
#         kubernetesCluster: 'akscni-cluster'
#         manifests: 'yamls/deploy-nginx.yaml'

# 
# - stage: check_env
#   jobs:
#   - deployment: check_environment
#     displayName: check_environment
#     environment: 
#       name: 'akscni-cluster-env'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: KubernetesManifest@0
#             inputs:
#               action: 'deploy'
#               # azureResourceGroup: 'akscni-rg'
#               # kubernetesCluster: 'akscni-cluster'
#               kubernetesServiceConnection: 'akscni-cluster-env-aksmonitor-cluster-default-1722231691092' # default resource in akscni-cluster-env
#               manifests: 'yamls/deploy-nginx.yaml'
#               namespace: 'default'
          # - task: Kubernetes@1
          #   inputs:
          #     connectionType: 'Azure Resource Manager'
          #     azureSubscriptionEndpoint: 'jacobmssub(6fb4629e-0776-431c-b528-96a47c03d872)'
          #     azureResourceGroup: 'akscni-rg'
          #     kubernetesCluster: 'akscni-cluster'
          #     namespace: 'default'
          #     command: 'get'
          #     arguments: 'pod'
          #     secretType: 'dockerRegistry'
          #     containerRegistryType: 'Azure Container Registry'