# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# resources:
#   repositories:
#   - repository: sampleapp
#     type: git
#     endpoint: JacobBaekHome
#     name: JacobBaekHome/sampleapp
variables:
  system.debug: 'true'

stages:
- stage: using_kubectl
  jobs:
  - job: kubectl_command
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'jenkins-user'
        namespace: 'default'
        command: 'get'
        arguments: 'pod'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
- stage: using_deploy_to_kubernetes
  jobs:
  - job: 
    steps:
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'azureResourceManager'
        azureSubscriptionConnection: 'jacobmssub(6fb4629e-0776-431c-b528-96a47c03d872)'
        azureResourceGroup: 'akscni-rg'
        kubernetesCluster: 'akscni-cluster'
        manifests: 'https://raw.githubusercontent.com/jacobbaek/k8sYamls/main/sampleNginx/xff.yaml'