# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# resources:
#   repositories:
#   - repository: sampleapp
#     type: git
#     endpoint: JacobBaekHome
#     name: JacobBaekHome/sampleapp

stages:
- stage: using_kubectl
  jobs:
  - job: kubectl_command
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'jenkins-user'
        namespace: 'default'
        command: 'get'
        arguments: 'pod'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'